export const charactersActionTypes = {
  FETCH_ALL_CHARACTERS: "FETCH_ALL_CHARACTERS",
  FETCH_ALL_CHARACTERS_COMPLETED: "FETCH_ALL_CHARACTERS_COMPLETED",
  SET_LIMIT: "SET_LIMIT",
  FETCH_ALL_CHARACTERS_ERROR: "FETCH_ALL_CHARACTERS_ERROR",
  FETCH_SINGLE_CHARACTER: "FETCH_SINGLE_CHARACTER",
  FETCH_EPISODES_FOR_SINGLE_CHARACTER: "FETCH_EPISODES_FOR_SINGLE_CHARACTER",
  SET_SELECT_VALUE: "SET_SELECT_VALUE",
  SWAP_ARRAYS: "SWAP_ARRAYS",
};

export const addCharactersActionTypes = {
  ADD_CHARACTER: "ADD_CHARACTER",
};

export const changeThemeActionTypes = {
  CHANGE_THEME: "CHANGE_THEME",
};
